export {default as DemoReel} from "./DemoReel"
export {default as Footer} from "./Footer"
export {default as Gallery} from "./Gallery/Gallery"
export {default as Header} from "./Header"
export {default as Intro} from "./Intro"
export {default as Services} from "./Services"
export {default as ContactForm} from "./ContactForm"
export {default as VisualDevGallery} from './VisualDev/VisualDevGallery'
export {default as ConceptArtGallery} from './ConceptArt/ConceptArtGallery'
