const Illustrations = [
    '/assets/ils/01.png',
    '/assets/ils/02.png',
    '/assets/ils/03.png',
    '/assets/ils/04.png',
    '/assets/ils/05.png',
    '/assets/ils/06.png',
    '/assets/ils/09.png',
    '/assets/ils/10.png',
    '/assets/ils/11.png',
    '/assets/ils/14.png',
    '/assets/ils/15.png',
    '/assets/ils/16.png',
    '/assets/ils/17.png',
    '/assets/ils/20.png',
    '/assets/ils/22.png',
    '/assets/ils/23.png',
    '/assets/ils/24.png',
    '/assets/ils/25.png',
    '/assets/ils/26.png',
]
export default Illustrations