const Slider = [
    {image: require('../../assets/ils/00.png'),
    alt: "image 0"},
    {image: require('../../assets/ils/01.png'),
    alt: "image 1"},
    {image: require('../../assets/ils/02.png'),
    alt: "image 2"},
    {image: require('../../assets/ils/03.png'),
    alt: "image 3"},
    {image: require('../../assets/ils/04.png'),
    alt: "image 4"},
    {image: require('../../assets/ils/05.png'),
    alt: "image 5"},
    {image: require('../../assets/ils/06.png'),
    alt: "image 6"},
    {image: require('../../assets/ils/07.png'),
    alt: "image 7"},
    {image: require('../../assets/ils/08.png'),
    alt: "image 8"},
    {image: require('../../assets/ils/09.png'),
    alt: "image 9"},
    {image: require('../../assets/ils/10.png'),
    alt: "image 10"},
    {image: require('../../assets/ils/11.png'),
    alt: "image 11"},
    {image: require('../../assets/ils/12.png'),
    alt: "image 12"},
    {image: require('../../assets/ils/13.png'),
    alt: "image 13"},
    {image: require('../../assets/ils/14.png'),
    alt: "image1 4"},
    {image: require('../../assets/ils/15.png'),
    alt: "image 15"},
    {image: require('../../assets/ils/16.png'),
    alt: "image 16"},
    {image: require('../../assets/ils/17.png'),
    alt: "image 17"},
    {image: require('../../assets/ils/18.png'),
    alt: "image 18"},
    {image: require('../../assets/ils/19.png'),
    alt: "image 19"},
    {image: require('../../assets/ils/20.png'),
    alt: "image 20"},
    {image: require('../../assets/ils/21.png'),
    alt: "image 21"},
    {image: require('../../assets/ils/22.png'),
    alt: "image 22"},
    {image: require('../../assets/ils/23.png'),
    alt: "image 23"},
]
export default Slider 