const Thumbnails = [
    {image: require('../../assets/ils_thumbs/00.png'),
    alt: "image 0"},
    {image: require('../../assets/ils_thumbs/01.png'),
    alt: "image 1"},
    {image: require('../../assets/ils_thumbs/02.png'),
    alt: "image 2"},
    {image: require('../../assets/ils_thumbs/03.png'),
    alt: "image 3"},
    {image: require('../../assets/ils_thumbs/04.png'),
    alt: "image 4"},
    {image: require('../../assets/ils_thumbs/05.png'),
    alt: "image 5"},
    {image: require('../../assets/ils_thumbs/06.png'),
    alt: "image 6"},
    {image: require('../../assets/ils_thumbs/07.png'),
    alt: "image 7"},
    {image: require('../../assets/ils_thumbs/08.png'),
    alt: "image 8"},
    {image: require('../../assets/ils_thumbs/09.png'),
    alt: "image 9"},
    {image: require('../../assets/ils_thumbs/10.png'),
    alt: "image 10"},
    {image: require('../../assets/ils_thumbs/11.png'),
    alt: "image 11"},
    {image: require('../../assets/ils_thumbs/12.png'),
    alt: "image 12"},
    {image: require('../../assets/ils_thumbs/13.png'),
    alt: "image 13"},
    {image: require('../../assets/ils_thumbs/14.png'),
    alt: "image1 4"},
    {image: require('../../assets/ils_thumbs/15.png'),
    alt: "image 15"},
    {image: require('../../assets/ils_thumbs/16.png'),
    alt: "image 16"},
    {image: require('../../assets/ils_thumbs/17.png'),
    alt: "image 17"},
    {image: require('../../assets/ils_thumbs/18.png'),
    alt: "image 18"},
    {image: require('../../assets/ils_thumbs/19.png'),
    alt: "image 19"},
    {image: require('../../assets/ils_thumbs/20.png'),
    alt: "image 20"},
    {image: require('../../assets/ils_thumbs/21.png'),
    alt: "image 21"},
    {image: require('../../assets/ils_thumbs/22.png'),
    alt: "image 22"},
    {image: require('../../assets/ils_thumbs/23.png'),
    alt: "image 23"},
]
export default Thumbnails