const VisualDev= {
    Busstop: [
    '/assets/visdev/busstop/01.jpg',
    '/assets/visdev/busstop/02.jpg',
    '/assets/visdev/busstop/03.jpg',
    '/assets/visdev/busstop/04.jpg',
    '/assets/visdev/busstop/05.jpg',
    '/assets/visdev/busstop/06.jpg',
    '/assets/visdev/busstop/07.jpg',
    ],
    Sync01: [
        '/assets/visdev/sync01/01.jpg',
        '/assets/visdev/sync01/02.jpg',
        '/assets/visdev/sync01/03.jpg',
        '/assets/visdev/sync01/04.jpg',
        '/assets/visdev/sync01/05.jpg',
        '/assets/visdev/sync01/06.jpg',
        '/assets/visdev/sync01/07.jpg',
        '/assets/visdev/sync01/08.jpg',
        '/assets/visdev/sync01/09.jpg',
        '/assets/visdev/sync01/10.jpg', 
        '/assets/visdev/sync01/11.jpg', 
    ],
    Sync07:[
        '/assets/visdev/sync07/01.jpg',
        '/assets/visdev/sync07/02.jpg',
        '/assets/visdev/sync07/03.jpg',
        '/assets/visdev/sync07/04.jpg',
        '/assets/visdev/sync07/05.jpg',
        '/assets/visdev/sync07/06.jpg',
        '/assets/visdev/sync07/07.jpg',
        '/assets/visdev/sync07/08.jpg',
        '/assets/visdev/sync07/09.jpg',
        '/assets/visdev/sync07/10.jpg',
        '/assets/visdev/sync07/11.jpg',
        '/assets/visdev/sync07/12.jpg',
        '/assets/visdev/sync07/13.jpg',
        '/assets/visdev/sync07/14.jpg',
        '/assets/visdev/sync07/15.jpg',
        '/assets/visdev/sync07/16.jpg',
        '/assets/visdev/sync07/17.jpg',
        '/assets/visdev/sync07/18.jpg',
    ]
}

export default VisualDev